# Generated by Django 3.0.6 on 2020-06-01 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mioserver', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imagePath',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mioserver.Image'),
        ),
    ]
