# Generated by Django 3.0.6 on 2020-06-03 12:14

from django.db import migrations, models
import mioserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('mioserver', '0002_remove_image_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(null=True, storage=mioserver.models.OverwriteStorage(), upload_to=mioserver.models.get_upload_to),
        ),
    ]
