# Generated by Django 3.0.6 on 2020-06-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mioserver', '0003_auto_20200601_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('static_dir', models.CharField(max_length=100)),
            ],
        ),
    ]
