# Generated by Django 3.0.6 on 2020-06-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mioserver', '0003_auto_20200603_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='nickname',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
